# Generated by Django 4.2.6 on 2023-10-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('slide_image_1', models.ImageField(blank=True, null=True, upload_to='mediaProduct/products')),
                ('slide_image_2', models.ImageField(blank=True, null=True, upload_to='mediaProduct/products')),
                ('slide_image_3', models.ImageField(blank=True, null=True, upload_to='mediaProduct/products')),
            ],
        ),
    ]
