# Generated by Django 4.2.6 on 2023-10-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
