# Generated by Django 4.2.6 on 2023-10-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='mediaProduct/products'),
        ),
        migrations.AddField(
            model_name='about',
            name='video_link',
            field=models.FileField(blank=True, null=True, upload_to='mediaProduct/video'),
        ),
    ]
