# Generated by Django 4.2.6 on 2023-10-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_about_image_about_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='mission_statement',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='vision_statement',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
