# Generated by Django 4.2.6 on 2023-10-15 23:00

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_mission_statement_about_vision_statement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='video_link',
        ),
        migrations.AddField(
            model_name='about',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
